easy_admin:
   entities:
       # List the entity class name you want to manage
      #  - App\Entity\Joueur
      #  - App\Entity\Agent
       - App\Entity\User
   site_name: FOOT MERCATO

   user:
        display_name: true
        display_avatar: false
        name_property_path: 'fullName'

   design:
        brand_color: '#1ABC9C'

      