#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#home:
#    path: /
#    controller: App\Controller\HomeController::index

#apropos:
#    path: /apropos
#    controller: App\Controller\AproposController::index

#contact:
#    path: /contact
#    controller: App\Controller\ContactController::addContact

#offres:
#    path: /offres
#    controller: App\Controller\OffresController::index

#joueur:
#    path: /joueur
#    controller: App\Controller\InscriptionJoueurController::addJoueur

#agent:
#    path: /agent
#    controller: App\Controller\InscriptionAgentController::addAgent

#club:
#    path: /club
#    controller: App\Controller\InscriptionClubController::addClub

#fichesjoueur:
#    path: /fichesjoueur
#    controller: App\Controller\FichesJoueurController::index

#app_login:
#    path: /login
#    controller: App\Controller\SecurityController::login





