#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#home:
#    path: /
#    controller: App\Controller\HomeController::index

#apropos:
#    path: /apropos
#    controller: App\Controller\AproposController::index

#contact:
#    path: /contact
#    controller: App\Controller\ContactController::index
